# SPDX-FileCopyrightText: 2023 Alec Delaney, written for Adafruit Industries
#
# SPDX-License-Identifier: MIT

repos:
  - repo: https://github.com/python/black
    rev: 22.3.0
    hooks:
      - id: black
        name: Format via black
  - repo: https://github.com/fsfe/reuse-tool
    rev: v0.14.0
    hooks:
      - id: reuse
        name: Check REUSE compatibility
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-json
        name: Check JSON
      - id: check-toml
        name: Check TOML
      - id: check-yaml
        name: Check YAML
      - id: end-of-file-fixer
        name: Ensure newline endings
      - id: mixed-line-ending
        name: Prevents mixed line endings
      - id: trailing-whitespace
        name: Trim trailing whitespace
