# SPDX-FileCopyrightText: 2023 Alec Delaney, written for Adafruit Industries
#
# SPDX-License-Identifier: MIT

name: 'Create CircuitPython filesystem for rp2040js'
author: Alec Delaney
description: |
  'Create a FAT12 filesystem for use in rp2040js when running CircuitPython.'
inputs:
  input-folder:
    description: 'A folder representing the filesystem to be created'
    required: true
  fs-name:
    description: 'A name for the filesystem image'
    required: true
    default: 'fat12.img'
  mount-folder:
    description: 'The name of the folder to which the FAT12 image will be mounted'
    required: true
    default: 'fat12mount'
outputs:
  fat12-image:
    description: 'Absolute filepath to the created FAT12 image'
    value: ${{ steps.create-fat12-file.outputs.fat12-image }}
runs:
  using: "composite"
  steps:
    - name: Create FAT12 file
      id: create-fat12-file
      shell: bash
      run: |
        truncate ${{ inputs.fs-name }} -s 1M
        mkfs.vfat -F12 -S512 ${{ inputs.fs-name }}
        imagefp=$(realpath ${{ inputs.fs-name }})
        echo "fat12-image=$imagefp" >> $GITHUB_OUTPUT
    - name: Mount the filesystem
      id: mount-filesystem
      shell: bash
      run: |
        mkdir ${{ inputs.mount-folder }}
        sudo mount -o loop ${{ inputs.fs-name }} ${{ inputs.mount-folder }}/
    - name: Copy files into image
      id: copy-files
      shell: bash
      run: |
        sudo cp ${{ inputs.input-folder }}/* -r ${{ inputs.mount-folder }}
    - name: Unmount the filesystem and remove fodler
      id: unmount-and-remove
      shell: bash
      run: |
        sudo umount ${{ inputs.mount-folder }}
        sudo rm -rf ${{ inputs.mount-folder }}
